// Mocks generated by Mockito 5.0.10 from annotations
// in vendor_mobile/test/mock/mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:core_package/core_module.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [BaseApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApiClient extends _i1.Mock implements _i2.BaseApiClient {
  MockBaseApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get(String? url,
          {String? token,
          dynamic responseType,
          Map<String, dynamic>? queryParams,
          Map<String, dynamic>? headers,
          int? msTimeout = 5000}) =>
      (super.noSuchMethod(
          Invocation.method(#get, [
            url
          ], {
            #token: token,
            #responseType: responseType,
            #queryParams: queryParams,
            #headers: headers,
            #msTimeout: msTimeout
          }),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> patch(String? url,
          {dynamic data,
          String? token,
          Map<String, dynamic>? headers,
          String? contentType = r'application/json',
          int? msTimeout = 5000}) =>
      (super.noSuchMethod(
          Invocation.method(#patch, [
            url
          ], {
            #data: data,
            #token: token,
            #headers: headers,
            #contentType: contentType,
            #msTimeout: msTimeout
          }),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(String? url,
          {dynamic data,
          String? token,
          Map<String, dynamic>? headers,
          String? contentType = r'application/json',
          int? msTimeout = 5000}) =>
      (super.noSuchMethod(
          Invocation.method(#post, [
            url
          ], {
            #data: data,
            #token: token,
            #headers: headers,
            #contentType: contentType,
            #msTimeout: msTimeout
          }),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(String? url,
          {dynamic data,
          String? token,
          Map<String, dynamic>? headers,
          String? contentType = r'application/json',
          int? msTimeout = 5000}) =>
      (super.noSuchMethod(
          Invocation.method(#delete, [
            url
          ], {
            #data: data,
            #token: token,
            #headers: headers,
            #contentType: contentType,
            #msTimeout: msTimeout
          }),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(String? url,
          {dynamic data,
          String? token,
          Map<String, dynamic>? headers,
          String? contentType = r'application/json',
          int? msTimeout = 5000}) =>
      (super.noSuchMethod(
          Invocation.method(#put, [
            url
          ], {
            #data: data,
            #token: token,
            #headers: headers,
            #contentType: contentType,
            #msTimeout: msTimeout
          }),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
